# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: docs:build
    
    - name: deploy
      run: git add -A
      run: git commit -m 'deploy'
      run: git push git@github.com:zkwolf/vitepress-starter.git master
